{% set name = "pcl" %}
{% set version = "1.9.0" %}
{% set sha256 = "40668357738d682c71929d7bc21a4db39312187855c6456751e2aae9dc6b29de" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pointcloudlibrary/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
  host:
    - flann
    - eigen
    - boost-cpp
  run:
    - flann
    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }}

test:
  commands:
    - test -d $PREFIX/include/{{ name }}-1.8/{{ name }}              # [not win]
    - if not exist %LIBRARY_INC%\\{{ name }}-1.8\\{{ name }} exit 1  # [win]
    - conda inspect linkages -p $PREFIX {{ name|lower }}             # [not win]
    - conda inspect objects -p $PREFIX {{ name|lower }}              # [osx]

about:
  home: http://www.pointclouds.org
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Point Cloud Library (PCL)'
  description: |
    The Point Cloud Library (PCL) is a standalone, large scale, open project for 2D/3D image and point cloud processing.
  doc_url: http://www.pointclouds.org
  dev_url: https://github.com/pointcloudlibrary/pcl

extra:
  recipe-maintainers:
    - chambbj
    - hobu
