{% set name = "pcl" %}
{% set version = "1.15.0" %}
{% set major_version = version.split(".")[0] %}
{% set minor_version = version.split(".")[1] %}
{% set sha256 = "e90c981c21e89c45201c5083db8308e099f34c1782f92fd65a0a4eb0b72c6fbf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pointcloudlibrary/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('pcl', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja                          # [win]
    - make                           # [unix]
    - pkgconfig
    - qt6-main                       # [build_platform != target_platform and not ppc64le]
  host:
    - xorg-libxfixes                 # [linux]
    - libgl-devel                    # [linux]
    - flann
    - eigen
    - libboost-devel
    - tbb-devel                      # [win]
    - qhull
    - vtk
    - libpng
    - glew
    - qt6-main  # [not ppc64le]
  run:
    - flann
    - qhull
    - glew

test:
  commands:
    - test -d $PREFIX/include/{{ name }}-{{ major_version }}.{{ minor_version }}/{{ name }}              # [not win] 
    - if not exist %LIBRARY_INC%\\{{ name }}-{{ major_version }}.{{ minor_version }}\\{{ name }} exit 1  # [win] 

about:
  home: http://www.pointclouds.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Cloud Library (PCL)
  description: |
    The Point Cloud Library (PCL) is a standalone, large scale, open project for 2D/3D image and point cloud processing.
  doc_url: http://www.pointclouds.org
  dev_url: https://github.com/pointcloudlibrary/pcl

extra:
  recipe-maintainers:
    - chambbj
    - hobu
    - Tobias-Fischer
    - traversaro
