{% set name = "pcl" %}
{% set version = "1.11.1" %}
{% set major_version = version.split(".")[0] %}
{% set minor_version = version.split(".")[1] %}
{% set sha256 = "a61558e53abafbc909e0996f91cfd2d7a400fcadf6b8cfb0ea3172b78422c74e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pointcloudlibrary/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
  host:
    - flann
    - eigen
    - boost-cpp
    - qhull 2019.1
  run:
    - flann
    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }}
    - qhull


test:
  commands:
    - test -d $PREFIX/include/{{ name }}-{{ major_version }}.{{ minor_version }}/{{ name }}              # [not win] 
    - if not exist %LIBRARY_INC%\\{{ name }}-{{ major_version }}.{{ minor_version }}\\{{ name }} exit 1  # [win] 
    - conda inspect linkages -p $PREFIX {{ name|lower }}             # [not win]
    - conda inspect objects -p $PREFIX {{ name|lower }}              # [osx]

about:
  home: http://www.pointclouds.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Cloud Library (PCL)
  description: |
    The Point Cloud Library (PCL) is a standalone, large scale, open project for 2D/3D image and point cloud processing.
  doc_url: http://www.pointclouds.org
  dev_url: https://github.com/pointcloudlibrary/pcl

extra:
  recipe-maintainers:
    - chambbj
    - hobu
    - Tobias-Fischer
