{% set name = "pcl" %}
{% set version = "1.10.0" %}
{% set sha256 = "dd24f93967ba9512a02d6fa15855084a45deb4cd6f3662f22afbbf0d65978d20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pointcloudlibrary/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - except.patch
    - flann.patch  # [osx]
    - boost1.70.patch

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
  host:
    - flann
    - eigen
    - boost-cpp
    - qhull
  run:
    - flann
    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }}
    - qhull


test:
  commands:
    - test -d $PREFIX/include/{{ name }}-1.9/{{ name }}              # [not win]
    - if not exist %LIBRARY_INC%\\{{ name }}-1.9\\{{ name }} exit 1  # [win]
    - conda inspect linkages -p $PREFIX {{ name|lower }}             # [not win]
    - conda inspect objects -p $PREFIX {{ name|lower }}              # [osx]

about:
  home: http://www.pointclouds.org
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Point Cloud Library (PCL)'
  description: |
    The Point Cloud Library (PCL) is a standalone, large scale, open project for 2D/3D image and point cloud processing.
  doc_url: http://www.pointclouds.org
  dev_url: https://github.com/pointcloudlibrary/pcl

extra:
  recipe-maintainers:
    - chambbj
    - hobu
