provider:
  osx: circle
travis:
  secure:
    BINSTAR_TOKEN: hV06WD+IGQdGQ5oCKmtRvlieBPWX5aiVWrxY5VMahzNRVIP8EZwEdw0bg+A1YaJ1xK1WXuTRUUqPDqMYrtSZqgUundxoBQUuIkilbZsu0X0mLyiKqhFHjmYdkuzpC16u2eQATPpJmTY29JEXnBf5PoLWO0gxKO6/qTJ78NTJVuRzobditSxlqT2f3RuBAsqU1ge3gSFuswDoZkHyparyT5jckC24bP1SpXcIiyK4H5EKHiBMTOWU4YRYqjUGj+JfePbYXqRxGE5EaUW5aSLwIFQBzKQlZikQsI8fsXWCRbHYpgHJcga93JL1Js8C32EKE8kH1Y2CtURNFpbMOy8hegfqQVrU5R34vpkYGUC1wFl4ILfNdpGyz0rMoa7Y4vvLJ0Mv9IW8BXRX0SqKkAfMgVIAJH717sn7FBmodh633cfg2tOPEsPtLLtH5J9M/nMQJv7ltDyZoUTyX/jXigFlsfZX4kZHgg/6TOBI0CGj1Spzdx5WckGuBiPkL7m/JlgODWNkZQfCW/BdTETu8Ht6DMUQYAy5YZLfClce82IW3DLoej+ZCCjDVyQ91IzjcvbeXZm1GhPfv6Tn36xotgfkAPsYvLtSSmVFiN4Pt2oQSRUuIdkInpQRhE/YYad4TsL8r9bG8bqeAc2uKxgZbsNR6acuQ1luacq6XtI/v9fUDGg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
