provider:
  osx: circle
travis:
  secure:
    BINSTAR_TOKEN: Lyg39rv4ZhlYqidx/+3/cdS0S4U7XkObVlyltDxPyFLm40FnI6/fBYZi0gfxYG5KTPrZb4y93a6oCo5a5+mIZnTpZHVYs0F4+nYZ8JjwknrpLj3o9yrqK0LjfyRU8C4RwPJlq8DDeqYy7eHLStTMZ0WfaR4kYrUAypL2nFf4jeZmkVEqrbd25fASWzjJvW2uAtabjbDvh3pvTY3h7OjeixnyZnzpGa3q49k44qD4hdhumNsmcNKqBYE0FALKXLm7zDUpj5Pr2+CH/twubaKGAyjIX/UsVl2RGPlbmQQTUBEKo2/Dh9myzGLDHJJlHreKFp9li1oif27uy+w/3Pqjy8OXrjRQU9gCmmtoQ9GpWtrSjP5N46gWiGw3vwWAocgCvI1b3qoXw7fhsCaMz1S4D+4VWNyydw5rJLjupK6RKFoCcfJ0BwHeSXUHYOB2dfnVhARcG/OE/3dr74MfGNxNUJdsl+NOSpzJ0AxWQGJOp1TsWs74XYaMrA2HeUDC8u0UCXu2msG8rl1yZYULqMho8eFZNopNei7YsS90ID4Zp4BMMKPa32wwLxqic9cBF6njkCqf8aGx5+Z++/eVPlRUTOWlrj7QeNQVzS2+RWMusWoyaVi/zm9HSgSeGzbL4HLg8jIjZhpj2HzULi03ciffBg5ppkdg4BYEOgV7/lYeMy0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
